### PR TITLE
Add destination page

### PR DESCRIPTION
**Pull request by tedmiston**
This just copies over the page I already wrote last week in Open.

(We should start thinking sometime soon about where this stuff should live that's common across the two repos.)

### CODE REVIEW

**Comment by schnie** [comment]
@ryw whacha think about these docs living in EE? Good stuff, just wondering if it's the place it should live.

**Comment by ryw** [comment]
i'll think about this today

**Comment by tedmiston** [comment]
Another idea is having a third "library" site for all the docs, but then these 2 sites would be pretty slim.

What about if the bulk of the deep reference content and guides live on the EE site and then the Open site is more just a brief tutorial + links out to EE docs as needed?

**Comment by tedmiston** [comment]
@ryw @schnie Do either of you have strong thoughts on whether common pages should live by default in EE or Open?  I lean towards EE with Open linking to them, but I don't have a strong opinion here.  Happy to go through the Open site and make these changes so we keep our guides DRY.

**Comment by schnie** [comment]
@tedmiston I like that plan. Keep bulk of docs in EE and link to them since most of it's EE related anyway.

**Comment by schnie** [comment]
Clickstream related - closing.

**Pull request closed without merging**
