### PR TITLE
Guide/building custom base images astronomer93

### PR DESCRIPTION
**Pull request by andscoop**
- adds docs on customization of EE images
- closes https://github.com/astronomerio/astronomer/issues/93

### CODE REVIEW

**Comment by tedmiston** [comment]
@andscoop Can you update the output to pass [markdownlint](https://github.com/markdownlint/markdownlint)?  (Lines of whitespace around code blocks, headers, etc.)  I have a few tweaks I want to make but I'll wait for this so we don't get merge conflicts.

**Comment by andscoop** [comment]
@tedmiston done

**Comment by andscoop** [comment]
@tedmiston Not sure what changes you have in mind - but are you okay with merging this and then you can contribute at your leisure. I want to get this out there for reference and close the issue for it?

**Comment by tedmiston** [comment]
I'll send commits back to you tomorrow

**Pull request merged**
