### PR TITLE
Use Astro branding

### PR DESCRIPTION
**Pull request by jlaneve**

### CODE REVIEW

**Comment by schnie** [comment]
@jlaneve just pulled this down to test. I'm getting an `Uncaught ReferenceError: trianglify is not defined` error on `dev` branch, but it works fine back on `master`.

Also looks like the `Sofia Pro` `font-family` isn't working. It's falling back to a standard `Serif`-looking font.

**Comment by jlaneve** [comment]
@schnie I’ll get those issues fixed, but I don’t see the trianglify error on my end. Can you confirm again that it’s an issue for you? Apologies for the late reply - I’ve been working with @gregbrunk on some issues he’s noticed regarding this PR as well, so I wanted to get those cleared up before moving to these.

**Comment by schnie** [comment]
@jlaneve still seeing it. Looks like the script downloads from a cloudflare url just fine. For some reason it's still spitting that error out in the console, and the effect doesn't show up. 

@gregbrunk does it work fine for you?

**Comment by pcmaffey** [comment]
@jlaneve 
1. the local assets aren't loading because they need to be `../assets/css` instead of `/assets/css`
2. you also need to load and define our custom fonts first before using them `@font-face` tag. Check out the code for how we do that in the website `src/styles/fonts.js`
3. When you do define them, be sure to use fallbacks: `font-family: 'Sofia Regular', 'Open Sans', Helvetica, Arial, sans-serif`
4. Looking at the trianglify script, the function is capitalized `Trianglify`.

**Comment by tedmiston** [comment]
@jlaneve If you don't want to deal with trying to catch every single external link with a `target="_blank"`, you can put this small js snippet in the base header to add target blanks dynamically client side automatically.

I have this snippet on my personal blog to achieve that.  Feel free to poke around if you want to try it.  https://blog.tedmiston.com

```javascript
<!-- Force external links to open in new tabs. Code from https://css-tricks.com/snippets/jquery/open-external-links-in-new-window/. -->
<script>
  $('a').each(function() {
    var a = new RegExp('/' + window.location.host + '/');
    if(!a.test(this.href)) {
      $(this).click(function(event) {
        event.preventDefault();
        event.stopPropagation();
        window.open(this.href, '_blank');
      });
    }
});
</script>
```

**Pull request merged**
